---
- hosts: all
  sudo: yes
  tasks:
    - name: Install Unzip
      apt:
        pkg: unzip    
    - name: Download Consul
      get_url:
        url: https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
        dest: /tmp/consul-0.5.2_linux_amd64.zip
    - name: Unzip Consul
      unarchive:
        src: /tmp/consul-0.5.2_linux_amd64.zip
        dest: /usr/local/bin
        copy: no
        group: root
        owner: root
        mode: 0755
    - name: Create consul config directory
      file:
        dest: /etc/consul.d
        state: directory
        owner: root
        group: root
        mode: 0644
    - name: Create consul lib directory
      file:
        dest: /var/lib/consul
        state: directory
        owner: root
        group: root
        mode: 0644
    - name: Generate consul configuration file
      template:
        src: config.json
        dest: /etc/consul.d/config.json
        owner: root
        group: root
        mode: 0644
    - name: Download Consul UI
      get_url:
        url: https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip
        dest: /tmp/consul-0.5.2_web_ui.zip
    - name: Create consul-ui dir
      file:
        name: /opt/consul/ui
        state: directory
    - name: Unzip Consul-UI
      unarchive:
        src: /tmp/consul-0.5.2_web_ui.zip
        dest: /opt/consul/ui
        copy: no
    - name: Copy the consul server init
      template:
        src: consul-server.conf.j2
        dest: /etc/init/consul-server.conf
        owner: root
        group: root
        mode: 0444
    - name: Start server
      service:
        name: consul-server
        state: restarted
        enabled: yes
    - name: Join cluster
      command: /usr/local/bin/consul join 192.168.10.10
